import type { Metadata } from "next";

import { Merriweather } from "next/font/google";
import "@/styles/globals.css";
import WhatsappButton from "@/components/WhatsappButton";

const merriweather = Merriweather({
  variable: "--font-merriweather",
  subsets: ["latin"],
  weight: ["300", "400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${merriweather.variable} antialiased scroll-smooth`}>
        <WhatsappButton />
        {children}
      </body>
    </html>
  );
}
